from enum import Enum


class ProjectStatus(Enum):
    DRAFT = 'DRAFT'
    SUBMITTED = 'SUBMITTED'
    APPROVED = 'APPROVED'
    CONDITIONALLY_APPROVED = 'CONDITIONALLY_APPROVED'
    REVISED = 'REVISED'
    REJECTED = 'REJECTED'
    ASSIGNED = 'ASSIGNED'
    COMPLETED = 'COMPLETED'
    ONGOING = 'ONGOING'
    SUSPENDED = 'SUSPENDED'
    IN_PIPELINE = 'IN_PIPELINE'
    POST_EVALUATION = 'POST_EVALUATION'
    